format_version: 3

pipelines:
  distribution-employee-mobile_automation-scripts_package:
    group: distribution-employee-mobile
    label_template: "${git[:8]}"
    lock_behavior: unlockWhenFinished
    tracking_tool:
      link: "https://cxagroup.atlassian.net/browse/${ID}"
      regex: "([A-Z]+-\\d+)"
    materials:
      git:
      git:
        type: git
        url: https://github.com/cxagroup/distribution-employee-mobile
        branch: master
        auto_update: true
        shallow_clone: true
    stages:
      - verify:
          clean_workspace: yes
          jobs:
            verify_repository:
              resources:
                - linux
              tasks:
                - script: |
                    bash -e pipeline/scripts/verify.sh
      - package:
          clean_workspace: yes
          resources:
            - linux
          artifacts:
            - build:
                source: ./
                destination: automation-scripts
          tasks:
            - script: |
                echo "Provides automation-scripts for downstream pipelines (ios / android promote pipelines)"
